language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  # allow_failures:
  #   - rust: nightly
  fast_finish: true

cache: cargo
script:
  - cargo build --verbose --all --features=wild
  - cargo test --verbose --all --features=wild
  - cargo bench